theme: jekyll-theme-minimal
title: Nathan's homepage
description: Hello! I'm Nathan, and I attended a Charter Highschool in Connecticut. I love skating, video games, trying out new things, exploring, and creating things.
